[project]
name = "paratranz-py"
version = "0.7.3"
description = "A simple ParaTranz Python Package"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru==0.7.3",
    "pooch==1.8.2",
]

[dependency-groups]
dev = [
    "ruff==0.9.9",
]
